### ISSUE TITLE
How to use TryCatch?

### ISSUE THREAD

**Issue by mbasmanova** [airlift/bytecode#6]
Is there an example of how to use the TryCatch class? I'm trying to figure out how to get access to the exception being caught?

CC: @electrum @tdcmeehan

**Comment by mengzhisy** [comment]
examples can be found at https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/scalar/MapTransformValueFunction.java#L245

**Comment by mbasmanova** [comment]
Thank you, @mengzhisy .

For future reference, this example was introduced in PR https://github.com/prestodb/presto/pull/13500

**Comment by mbasmanova** [comment]
CC: @wenlei @NikhilCollooru
